config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'pages#home'
  #pages
  get 'about',     to: 'pages#about'
  post 'search',    to: 'books#search_book'
  get 'donated',    to: 'pages#donated'
  #users
  get 'signup',    to: 'users#new'
  post 'signup',   to: 'users#create'
  get 'users',     to: 'users#index'
  #books
  get 'search',     to: 'books#search_book'
  get 'author',     to: 'books#all_by_author'
  get 'location',   to: 'books#all_by_location'
  get 'landscape',  to: 'books#all_by_landscape'
  get 'genre',      to: 'books#all_by_genre'
  get 'tag',        to: 'books#all_by_tag'
  get 'books/new',  to: 'books#new'
  post 'books/new', to: 'books#create'
  get 'books/add',  to: 'books#add'
  post 'books/add', to: 'books#googlebooks_search'

  #session
  get 'login',     to: 'sessions#new'
  post 'login',    to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :users
  resources :books
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  attr_accessor :query
  validates :user_id, presence: true
  validates :author, presence: true, length: {minimum: 4, maximum: 100}
  validates :title, presence: true, length: {minimum: 2, maximum: 150}
  validates :quality, presence: true, length: {maximum: 15}
  validates :genre, presence: true, length: {maximum: 30}
  validates :language, presence: true, length: {maximum: 30}

   before_validation { self.language = expand_language_code }
   before_validation { self.language = language.capitalize if language.present? }

  def self.search(query)
    unless query.nil?
      query.downcase!
      query.strip!
      query = "%#{query}%"
      where("LOWER(author) LIKE ?", query)
        .or(where("LOWER(title) LIKE ?", query))
        .or(where("LOWER(genre) LIKE ?", query))
        .or(where("LOWER(tags) LIKE ?", query))
    end
  end

  private

  def expand_language_code
    case language
    when 'sv'
      'Svenska'
    when 'en'
      'Engelska'
    when 'da'
      'Danska'
    when 'no'
      'norska'
    when 'fi'
      'Finska'
    else
      language
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'will_paginate/array'

  before_action :load_book_or_redirect, only: %i[show edit]
  before_action :logged_in_user, only: [:create, :new, :edit, :add, :googlebooks_search]
  before_action :authorize_user, only: [:update, :destroy]

  def show; end

  def new
    @book = Book.new
  end

  def edit
    redirect_to root_path unless allowed_to_edit?
  end

  def update
    @book = Book.find_by("id = ?", params[:id])

    @auth = (current_user == @book.user || current_user.admin?)
    if @auth && @book.update_attributes(book_params)
      if current_user.admin
        flash[:success] = "Bok #{@book.id}:s information har nu uppdaterats"
        redirect_to @book
      else
      flash[:success] = "Bokens information har nu uppdaterats"
      redirect_to @book
      end
    elsif !@auth
      render 'root_url'
    else
      render 'edit'
    end
  end

  def create
    @book = current_user.books.build(book_params)

    if current_user.disabled?
      flash[:danger] = "Du kan inte lägga upp böcker, eftersom ditt konto är avstängt"
      redirect_to root_url
    elsif !current_user.activated?
      flash[:danger] = "Du kan inte lägga upp böcker, eftersom du inte har aktiverat ditt konto"
      redirect_to root_url
    elsif @book.save
      flash[:success] = "Boken har lagts upp!"
      redirect_to @book
    else
      render 'new'
    end
  end

  def destroy
    @book = Book.find_by("id = ?", params[:id])
    if (current_user.admin?)
      @book.destroy
      flash[:success] = "Boken har raderats"
      redirect_to root_url
    elsif (current_user == @book.user)
      @book.destroy
      flash[:success] = "Din bok har nu tagits bort från Biblion"
      redirect_to root_url
    else
      render 'root_url'
    end
  end

  def add
    @book = Book.new
  end

  def googlebooks_search
    @query = search_params[:query]
    @book = Book.new
    @books = []
    books = GoogleBooks.search(@query, {:count => 30})
    books.each do |book|
      tls_img = book.image_link(:zoom => 2)
      if !tls_img.nil? and !tls_img ["http:"].nil?
        tls_img ["http:"] = "https:"
      end

      @books.push(
        Book.new(
          author: book.authors,
          title: book.title,
          description: book.description,
          cover: tls_img,
          language: book.language,
          user: current_user,
          googlebooks: book.info_link,
          pages: book.page_count
        )
      )
    end
    
    render 'add'
  end

  def all_by_author
    @books = Book.where("author =  ? and donated = ?", params[:author], false)
    @count = @books.count
    @books = @books.paginate(page: params[:page])
    @author = params[:author]
  end

  def search_book
    if request.get?
      redirect_to root_url
    else
      @query = search_params[:query]
      @books = Set.new Book.search(@query).order("created_at DESC").to_a().select { |b| !b.donated }
      @users = User.search(@query).order("created_at DESC").to_a()
      @users.each do |u|
        u.books.each do |b|
          if !b.donated
            @books.add(b)
          end
        end
      end
      @books = @books.to_a()
      render 'search'
    end
  end

  def all_by_genre
    @books = Book.where("genre =  ? AND donated = ?", params[:genre], false)
    @count = @books.count
    @books = @books.paginate(page: params[:page])
    @genre = params[:genre]
  end

  def all_by_tag
    @books = Book.where("LOWER(tags) LIKE ? AND donated = ?", "%#{params[:tags]}%", false)
    @count = @books.count
    @books = @books.paginate(page: params[:page])
    @tag = params[:tags]
  end

  def all_by_location
    @users = User.where("location =  ?", params[:location])
    @books = []
    @users.each do |u|
      u.books.each do |b|
        if !b.donated
          @books |= [b]
        end
      end
    end
    @count = @books.count
    @books = @books.paginate(page: params[:page])
    @location = params[:location]
  end

  def all_by_landscape
    @users = User.where("landscape =  ?", params[:landscape])
    @books = []
    @users.each do |u|
      u.books.each do |b|
        if !b.donated
          @books.push(b)
        end
      end
    end
    @count = @books.count
    @books = @books.paginate(page: params[:page])
    @landscape = params[:landscape]
  end

  private

    def allowed_to_edit?
      @book.user == current_user || current_user.admin?
    end

    def load_book_or_redirect
      @book = Book.find_by id: params[:id]
      redirect_to root_url if @book.nil?
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Vänligen logga in."
        redirect_to login_url
      end
    end

    def authorize_user
        @book = Book.find_by("id = ?", params[:id])
        if @book.nil?
          redirect_to root_url
        else
          redirect_to(root_url) unless logged_in? && (@book.user == current_user || current_user.admin?)
        end
    end

    def book_params
      params.require(:book).permit(:title, :author, :year, :description, :comment, :cover, :language, :quality, :genre, :googlebooks, :pages, :tags, :donated)
    end

    def search_params
      params.require(:book).permit(:query)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<li id="book-<%= book.id %>" class="col-sm-6 col-md-6 col-lg-4 container-fluid book">
  <div class="left col-md-4 col-sm-6 col-xs-4">
    <div class="cover-image">
      <div class="image-container">
      <%= link_to book do %>
        <% if book.cover.nil? || book.cover.empty? %>
          <% r = rand(4)+1 %>
          <%= image_tag("bookcover#{r}.png", alt: "Bokomslag för #{book.title}") %>
        <% else%>
          <%= image_tag(book.cover, alt: "Bokomslag för #{book.title}") unless book.cover.empty?%>
        <% end %>
      <% end %>
          <% if book.donated %>
      <h6 class="donated">Donerad!</h6>
    <% end %>
    </div>
    </div>
  </div>
  <div class="right col-md-8 col-sm-6 col-xs-8">

    <h4 class="title"><%=link_to book.title, book%></h4>
    <h5 class="author"><%= link_to book.author, author_url(author: book.author) %></h5>


    <h6 class="author">Skick: <%=  book.quality %></h6>
    <% if book.language.nil? || book.language.empty? %>
      <h6 class="year">Språk: Ej angivet</h6>
    <% else %>
      <h6 class="year">Språk: <%= book.language %></h6>
    <% end %>
    <% if book.genre.nil? || book.genre.empty? %>
      <h6 class="year">Genre: Ej angivet</h6>
    <% else %>
      <h6 class="year">Genre: <%= link_to book.genre, genre_url(genre: book.genre)%></h6>
    <% end %>
    <% unless book.tags.nil? || book.tags.empty? %>
      <h6 class="tags"><span class="attr">Taggar:</span>
        <span class="info">
          <% tags = book.tags.split(/,/) %>
          <% tags.each do |tag| %>
            <%= link_to '#' + tag.strip.downcase, tag_url(tags: tag.strip.downcase)%>
          <% end %>
        </span>
      </h6>
    <% end %>
    <% unless book.pages.nil? %>
      <h6 class="pages"><%= book.pages %> sidor</h6>
    <% end %>
    <h6 class="location">Ort:
      <%= link_to book.user.location, location_url(location: book.user.location)%>,
      <%= link_to book.user.landscape, landscape_url(landscape: book.user.landscape)%>
    </h6>
    
    <% if logged_in? %>
    <h6 class="created_at">Lades upp: <%= book.created_at.to_formatted_s(:dmy) %></h6>
    <% end %>
  </div>
</li>

app/views/books/add.html.erb
<%= provide(:title, 'Lägg till en ny bok') %>
<h1><%= yield(:title) %></h1>
<div class="row">
  <div class="action-form">
    <%= form_for(@book, url: {action: "googlebooks_search"}, method: :post) do |f| %>
      <%= f.label(:query, "Sök efter titel eller författare:") %>
      <%= f.text_field :query, autofocus: "true", onFocus: "this.select()", value: @query, class: "google-search",
      onkeyup: 'this.style.background=(this.value=="" ? "white url(https://developers.google.com/books/images/google_watermark.gif) no-repeat" : "white url(none) no-repeat");',
      onsubmit: 'this.style.background=(this.value=="" ? "white url(https://developers.google.com/books/images/google_watermark.gif) no-repeat" : "white url(none) no-repeat");' %>
      <%= f.submit("Sök") %>
      <% if params[:action] == "googlebooks_search" %>
        <p> Hittar du inte boken? Pröva en annan sökning, eller <%= link_to "lägg till den manuellt istället", new_book_path %>
      <% end %>
    <% end %>
  </div>
    <% unless @books.nil? %>
    <ul class="books">
    <% @books.each_with_index do |book, index| %>
      <li class="col-sm-6 col-md-6 col-lg-4 container-fluid select" onClick="document.forms.namedItem('form-<%= index %>').submit();">
        <%= form_for(book, url: {action: "new"}, method: :post, html: {id: "form-#{index}" }) do |f| %>
          <%= f.hidden_field :author, value: book.author %>
          <%= f.hidden_field :title, value: book.title %>
          <%= f.hidden_field :language, value: book.language %>
          <%= f.hidden_field :cover, value: book.cover %>
          <%= f.hidden_field :description, value: book.description %>
          <%= f.hidden_field :googlebooks, value: book.googlebooks %>
          <%= f.hidden_field :pages, value: book.pages %>
        <% end %>
        <div class="left col-md-4 col-sm-6">
            <div class="cover-image">
              <% r = rand(4)+1 %>
              <%= image_tag "bookcover#{r}.png" if book.cover.nil? %>
              <%= image_tag book.cover unless book.cover.nil?%>
            </div>
        </div>
        <div class="right col-md-8 col-sm-6">
          <h4 class="title"><%= book.title %></h4>
          <h5 class="author"><%= book.author %></h5>
          <% unless book.pages.nil? %>
            <h6 class="year"><%= book.pages %> sidor</h6>
          <% end %>
        </div>
      </li>
    <% end %>
    <% end %>
  </ul>
</div>

app/views/books/all_by_author.html.erb
<% provide(:title, @author) %>
<div class="col-md-12">
    <h3>Alla tillgängliga böcker skrivna av <%= @author %> (<%= @count %>)</h3>
    <ul class="books">
      <%= render @books %>
    </ul>
    <div class="pagination">
      <%= will_paginate @books, previous_label: t("föregående"), next_label: t("nästa")%>
    </div>
</div>

app/views/books/all_by_genre.html.erb
<% provide(:title, @genre) %>
<div class="col-md-12">
    <h3>Alla tillgängliga böcker inom <%= @genre %> (<%= @count %>)</h3>
    <ul class="books">
      <%= render @books %>
    </ul>
    <div class="pagination">
      <%= will_paginate @books, previous_label: t("föregående"), next_label: t("nästa")%>
    </div>
</div>

app/views/books/all_by_landscape.html.erb
<% provide(:title, @landscape) %>
<div class="col-md-12">
    <h3>Alla tillgängliga böcker i <%= @landscape %> (<%= @count %>)</h3>
    <ul class="books">
      <%= render @books %>
    </ul>
    <div class="pagination">
      <%= will_paginate @books, previous_label: t("föregående"), next_label: t("nästa")%>
    </div>
</div>

app/views/books/all_by_location.html.erb
<% provide(:title, @location) %>
<div class="col-md-12">
    <h3>Alla tillgängliga böcker i <%= @location %> (<%= @count %>)</h3>
    <ul class="books">
      <%= render @books %>
    </ul>
    <div class="pagination">
      <%= will_paginate @books, previous_label: t("föregående"), next_label: t("nästa")%>
    </div>
</div>

app/views/books/all_by_tag.html.erb
<% provide(:title, @tag) %>
<div class="col-md-12">
  <h3>Alla tillgängliga böcker som matchar taggen <%= link_to '#' + @tag.strip, tag_url(tags: @tag.strip)%> (<%= @count %>)</h3>
  <ul class="books">
    <%= render @books %>
  </ul>
  <div class="pagination">
    <%= will_paginate @books, previous_label: t("föregående"), next_label: t("nästa")%>
  </div>
</div>

app/views/books/edit.html.erb
<%= provide(:title, 'Redigera bokinformation') %>
<h1><%= yield(:title) %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="action-form">
      <% 
        file = File.open("#{Rails.root.to_s}/app/views/shared/genres.txt") or die 
        @genres = []
        file.each_line{|line|
          @genres.push(line.strip)
        }
      %>
      <%= form_for(@book) do |f| %>
        <%= render 'shared/book_error_messages' %>
        <%= f.label :title, "Boktitel" %>
        <%= f.text_field :title %>
        <%= f.label :author, "Författare" %>
        <%= f.text_field :author %>
        <%= f.label :language, "Språk" %>
        <%= f.text_field :language %>
        <%= f.label :quality, "Skick" %>
        <%= f.select :quality, options_for_select(['Använd', 'Nyskick', 'Sliten', 'Mycket sliten'], @book.quality), { :include_blank => '-- Ange skick --' } %>
        <%= f.label :genre, "Genre" %>
        <%= f.select :genre, options_for_select(@genres,  @book.genre), { :include_blank => '-- Välj en genre --' } %>
        <%= f.label :genre, "Sidor" %>
        <%= f.text_field :pages %>
        <%= f.label :year, "Utgivningsår" %>
        <%= f.date_select "year", include_blank: true, start_year: Time.now.year, end_year: Time.now.year - 200, order: [:year]%>
        <% if current_user.admin %>
          <%= f.label :description, "Beskrivning" %>
          <%= f.text_field :description %>
        <% end %>
        <%= f.label :comment, "Din kommentar om boken" %>
        <%= f.text_field :comment %>
        <%= f.label :tags, "Taggar (separera med kommatecken)" %>
        <%= f.text_area :tags, placeholder: "Ex. kurskoder eller subgenrer" %>
        <%= f.submit "Bekräfta ändringar", class: "btn btn-primary" %>

      <% end %>
  </div>
  </div>
</div>

app/views/books/new.html.erb
<%= provide(:title, 'Lägg till en ny bok') %>
<h1><%= yield(:title) %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="action-form">
      <% 
      file = File.open("#{Rails.root.to_s}/app/views/shared/genres.txt") or die 
      @genres = []
      file.each_line{|line|
        @genres.push(line.strip)
      }
      %>
      <%= form_for(@book, url: {action: "new"}, method: :post) do |f| %>
        <%= render 'shared/book_error_messages' %>
        <%= f.hidden_field :googlebooks %>
        <%= f.hidden_field :description %>
        <%= f.hidden_field :cover %>
        <%= f.hidden_field :pages %>
        <%= f.label :title, "* Boktitel" %>
        <%= f.text_field :title%>
        <%= f.label :author, "* Författare" %>
        <%= f.text_field :author%>
        <%= f.label :language, "* Språk" %>
        <%= f.text_field :language %>
        <%= f.label :quality, "* Skick" %>
        <%= f.select :quality, options_for_select(['Använd', 'Nyskick',
          'Sliten', 'Mycket sliten']), { :include_blank => '-- Ange skick --' } %>
        <%= f.label :genre, "* Genre" %>
        <%= f.select :genre, options_for_select(@genres), { :include_blank => '-- Välj en genre --' } %>
        <%= f.label :year, "Utgivningsår" %>
        <% if params[:year].nil? %>
          <%= f.date_select "year", include_blank: true, start_year: Time.now.year,
          end_year: Time.now.year - 200, order: [:year]%>
        <% else %>
          <%= f.date_select "year",
          default: DateTime.strptime(params[:year], '%Y-%m-%d %H:%M:%S %Z'),
          start_year: Time.now.year, end_year: Time.now.year - 200, order: [:year]%>
        <% end %>
        <%= f.label :pages, "Antal sidor" %>
        <%= f.text_field :pages %>
        <%= f.label :comment, "Din kommentar om boken" %>
        <%= f.text_area :comment %>
        <%= f.label :tags, "Taggar (separera med kommatecken)" %>
        <%= f.text_area :tags, placeholder: "Ex. kurskoder eller subgenrer" %>
        <%= f.submit "Lägg till boken!", class: "btn btn-primary" %>
      <% end %>
  </div>
  </div>
</div>

app/views/books/search.html.erb
<% provide(:title, "Sökning") %>
<div class="col-md-12">
    <h3>Alla tillgängliga böcker som matchar sökningen <%= params[:query] %> (
      <% unless @books.nil? %>
        <%= @books.count %>
      <% else %>
        0
      <% end %>
      )</h3>
    <ul class="books">
      <%unless @books.nil? %>
        <%= render @books %>
    </ul>
    <% end %>
</div>
<script>


/* 
Source: https://stackoverflow.com/questions/3115150/how-to-escape-regular-expression-special-characters-using-javascript
*/
function escapeRegExp(text) {
  return text.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
}
/* 
Source: https://j11y.io/snippets/highlighting-text-with-javascript/
*/
function highlight(container,what,spanClass) {
    what = escapeRegExp(what);
    var content = container.innerHTML,
        pattern = new RegExp('(>[^<.]*)(' + what + ')([^<.]*)','gi'),
        replaceWith = '$1<span ' + ( spanClass ? 'class="' + spanClass + '"' : '' ) + '">$2</span>$3',
        highlighted = content.replace(pattern,replaceWith);
    return (container.innerHTML = highlighted) !== content;
}

var books = document.getElementsByClassName("book");
for (var i = 0, len = books.length; i < len; i++) {
  highlight(books[i], "<%= @query %>", 'highlight');
}
</script>

app/views/books/show.html.erb
<% provide(:title, @book.title) %>
<div id="book-<%= @book.id %>" class="show-book">
  <div class="center_container col-lg-5 col-md-5 col-sm-4">
    <% if @book.cover.nil? or @book.cover.empty? %>
    <% r = rand(4)+1 %>
    <%= image_tag("bookcover#{r}.png", alt: "Bokomslag för #{@book.title}") %>
    <% else %>
    <%= image_tag(@book.cover, alt: "Bokomslag för #{@book.title}")%>
    <% end %>
  </div>

  <div class="col-lg-7 col-md-7 col-sm-8">
    <h2 class="title"><%=link_to @book.title, @book%></h2>
    <h4 class="author"><%= link_to @book.author, author_url(author: @book.author) %></h4>
    <ul>
    <li class="quality"><span class="attr">Skick:</span> <span class="info"><%=  @book.quality %></span></li>

    <% if @book.language.nil? || @book.language.empty?%>
    <li class="year"><span class="attr">Språk:</span> <span class="info">Ej angivet</span></li>
    <% else %>
    <li class="year"><span class="attr">Språk:</span> <span class="info"><%= @book.language %></span></li>
    <% end %>

    <% if @book.genre.nil? || @book.genre.empty? %>
    <li class="genre"><span class="attr">Genre:</span> <span class="info">Ej angivet</span></li>
    <% else %>
    <li class="genre"><span class="attr">Genre:</span> <span class="info"><%= link_to @book.genre, genre_url(genre: @book.genre)%></span></li>
    <% end %>

    <% unless @book.tags.nil? || @book.tags.empty? %>
      <li class="tags"><span class="attr">Taggar:</span>
        <span class="info">
          <% tags = @book.tags.split(/,/) %>
          <% tags.each do |tag| %>
            <%= link_to '#' + tag.strip.downcase, tag_url(tags: tag.strip.downcase)%>
          <% end %>
        </span>
      </li>
    <% end %>

    <% if @book.pages.nil?%>
    <li class="year"><span class="attr">Sidor:</span> <span class="info">Ej angivet</span></li>
    <% else %>
    <li class="year"><span class="attr">Sidor:</span> <span class="info"><%= @book.pages %></span></li>
    <% end %>

    <% if @book.year.nil? %>
    <li class="year"><span class="attr">Utgivningsår:</span> <span class="info">Ej angivet</span></li>
    <% else %>
    <li class="year"><span class="attr">Utgivningsår:</span> <span class="info"><%= @book.year.to_formatted_s(:y) %></span></li>
    <% end %>

    <li class="location"><span class="attr">Ort:</span>
      <span class="info">
      <%= link_to @book.user.location, location_url(location: @book.user.location)%>,
      <%= link_to @book.user.landscape, landscape_url(landscape: @book.user.landscape)%>
      </span>
    </li>
    <% if logged_in? %>
      <li class="givenby">
        <span class="attr">Ges bort av:</span>
        <span class="info"><%= link_to @book.user.name, @book.user %></span>
      </li>
    <% end %>
    <li class="googlebooks">
      <% unless @book.googlebooks.nil? || @book.googlebooks.empty? || !@book.googlebooks %>
        <span class="attr">Information hämtad från:</span><span class="info"><%= link_to "Google", @book.googlebooks, :target => "_blank", :rel => "noopener" %></span>
      <% end %>
  </li>
  </ul>
    <% if logged_in? %>
      <% if current_user == @book.user || current_user.admin %>
        <form action="<%= edit_book_path(@book) %>">
          <input type="submit" class="btn btn-primary" value="Redigera bokinformation"></input>
        </form>
        <% if @book.donated? %>
          <button type="button" class="btn btn-success">
            Boken är donerad
          </button>
        <% else %>
          <%= form_for @book, method: :patch do |f| %>
            <%= f.hidden_field :donated, value: true %>
            <%= f.submit "Markera som donerad", data: { confirm: "Är du säker på att du vill markera boken som donerad?" }, class: "btn btn-primary btn-success" %>
          <% end %>
        <% end %>
        
        <%= form_for @book, method: :delete do |f| %>
          <%= f.submit "Radera den här boken", data: { confirm: "Är du säker på att du vill radera boken?" }, class: "btn btn-primary btn-danger" %>
        <% end %>
      <% end %>
      <% if current_user != @book.user %>
        <% if current_user.disabled %>
          <button type="button" class="btn btn-primary btn-danger">
            Ditt konto är avstängt
          </button>
        <% elsif !current_user.activated %> 
          <button type="button" class="btn btn-primary btn-danger">
            Du har inte aktiverat ditt konto
          </button>
        <% else %>
          <% if @book.donated? %>
            <button type="button" class="btn btn-success">
              Boken är donerad
            </button>
          <% else %>
          <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#request">
            Kontakta ägaren<span class="caret"></span>
          </button>
          <div class="collapse info-col-list" id="request">
            <ul>
              <li><span>För att få boken måste du skicka ett mail till bokens ägare.</span></li>
              <li><span>Glöm inte att skriva i mailet att du gärna skulle vilja få boken <%= link_to @book.title, @book %>,
                som <%= link_to  @book.user.name.partition(" ").first, @book.user %> har lagt upp på Biblion. </span></li>
              <li><span>  
                Här är en textmall du kan använda:
              </span></li>
              <li><span>
                Hej <%= @book.user.name %>, jag såg din bok <a href="<%=  request.original_url %>"><%= @book.title %> på Biblion</a> och skulle gärna vilja läsa den!
                Kan du träffas en dag i <%= @book.user.location %> för att ge bort boken? <br/>
                Mvh <%= current_user.name %>.
              </span></li>
              <li><span>Namn </span><span><%= @book.user.name %></span></li>
              <li><span>Email </span>
                <span>
                  <%= mail_to @book.user.email, nil,  
                      {subject: "Biblion: förfrågan om din bok #{@book.title}",
                      body: "Hej #{@book.user.name}, jag såg din bok #{@book.title} som du lagt upp på Biblion och skulle gärna vilja läsa den! \nKan du träffas en dag i #{@book.user.location} för att ge bort boken? \nMvh #{current_user.name}"} %>
                </span>
              </li>
              
            </ul>
          </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <% unless @book.comment.nil? || @book.comment.empty? %>
    <h4>Ägarens kommentar:</h4> <p class="description"><%= @book.comment unless @book.comment.nil? %></p>
  <% end %>
  <% unless @book.description.nil? || @book.description.empty? %>
    <h4>Beskrivning:</h4> <p class="description"><%= @book.description%></p>
  <% end %>
  </div>
</div>