config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'pages#home'
  #pages
  get 'about',     to: 'pages#about'
  post 'search',    to: 'books#search_book'
  get 'donated',    to: 'pages#donated'
  #users
  get 'signup',    to: 'users#new'
  post 'signup',   to: 'users#create'
  get 'users',     to: 'users#index'
  #books
  get 'search',     to: 'books#search_book'
  get 'author',     to: 'books#all_by_author'
  get 'location',   to: 'books#all_by_location'
  get 'landscape',  to: 'books#all_by_landscape'
  get 'genre',      to: 'books#all_by_genre'
  get 'tag',        to: 'books#all_by_tag'
  get 'books/new',  to: 'books#new'
  post 'books/new', to: 'books#create'
  get 'books/add',  to: 'books#add'
  post 'books/add', to: 'books#googlebooks_search'

  #session
  get 'login',     to: 'sessions#new'
  post 'login',    to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :users
  resources :books
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<nav  class="navbar navbar-default navbar-fixed-bottom">

  <ul class="nav navbar-right navbar-nav footer">
    <li><%= link_to "Antal donerade böcker: #{Book.where("donated = ?", true).count}", donated_path %></li>
    <li><%= link_to "Om Biblion", about_path %></li>
    <li><a href="https://github.com/johan-andersson01/biblion">Github</a></li>
  </ul>
</nav>

app/views/layouts/_header.html.erb
<header>
<nav  class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse_me">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <span id="title">
          <%= link_to "Biblion", root_url %></span>
        </span>
        <% if false %>
          <span id="subtitle">
            BETA
          </span>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="collapse_me">
      <ul class="nav navbar-nav">
        <ul class="header-search-form">
        <li>
            <%= form_for(Book.new, url: {controller: "books", action: "search_book"}, method: :post) do |f| %>
                <%= f.text_field :query, value: params[:query], onFocus: "this.select()", placeholder: "Sök efter författare, titel, genre, tagg, stad, eller län" %>
        </li>
        <li>
          <%= f.submit("") %>
          <% end %>
        </li>
      </ul>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
            <li><%= link_to 'Registrera dig', signup_path %></li>
            <li><%= link_to 'Logga in', login_path %></li>
        <% else %>
          <li><%= link_to 'Lägg till en bok', books_add_path %></li>
          <li class="dropdown">
            <% if current_user.admin? %>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Admin<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profil', current_user %></li>
                <li><%= link_to 'Inställningar', edit_user_path(current_user) %></li>
                <li><%= link_to 'Användare', users_path %></li>
                <li><%= link_to "Logga ut", logout_path, method: :delete %></li>
              </ul>
            <% else %>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span>Meny</span><span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profil', current_user %></li>
                <li><%= link_to 'Inställningar', edit_user_path(current_user) %></li>
                <li><%= link_to "Logga ut", logout_path, method: :delete %></li>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/_login.html.erb
<div class="action-form">
<%= form_for(:session, url: login_path) do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "Lösenord" %>
  <%= link_to "(glömt lösenordet?)", new_password_reset_path %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.submit "Logga in", class: "btn btn-primary" %>
  <div class="checkbox-field">
    <%= f.label :remember_me, "Kom ihåg mig på den här enheten", class: "checkbox-inline"%>
    <%= f.check_box :remember_me, class: "checkbox" %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="sv">
  <head>
    <title>Biblion | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <meta name="google-site-verification" content="sthr8ei4f8LsG-T4j8vXf4bizRkUmLnfUyVXbRK5ynY" />
    <meta name="description" content="På Biblion kan du ge och få böcker av andra människor, helt gratis! Registrera dig för att börja, eller ta en titt för att se vilka
    böcker som ligger ute just nu.">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main-content">
      <% flash.each do |msg_type, msg| %>
      <div class="alert alert-<%= msg_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
    <!--<div class="debug"> <%= debug(params) if Rails.env.development? %></div>-->
    <%= render 'layouts/footer' %>
  </body>
</html>